filebeat.inputs:
  - type: docker
    combine_partial: true
    containers:
      path: "/usr/share/dockerlogs/data"
      stream: "stdout"
      ids:
        - "*"
    exclude_files: ['\.gz$']
    ignore_older: 10m

processors:
  - decode_json_fields:
      fields: ["log", "message", "msg"]
      target: ""
      overwrite_keys: true
  - add_docker_metadata:
      host: "unix:///var/run/docker.sock"
  - drop_fields:
      fields: ["container.labels.io_buildpacks_build_metadata", "container.labels.io_buildpacks_lifecycle_metadata", "container.labels.io_buildpacks_stack_id"]

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info
logging.to_files: false
logging.to_syslog: false
logging.metrics.enabled: false
ssl.verification_mode: none
