global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'spring-app'
    metrics_path: '/v1/api/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8887']
        labels:
          application: spring-app

