{
 "title": "Order Application Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "timeRate",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "API Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "data" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"spring-app\",method=~\".+\",status=~\"2.+\",uri=~\"/v1/api.*\"}[1m]))",
     "legendFormat": "SUCCESS"
    },
    {
     "expr": "sum(increase(http_server_requests_seconds_count{job=\"spring-app\",method=~\".+\",status!~\"2.+\",uri=~\"/v1/api.*\"}[1m]))",
     "legendFormat": "ERROR"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(rate(process_cpu_usage[1m])) * 100",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Heap Memory Usage",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "data" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(jvm_memory_used_bytes{area=\"heap\"}) / avg(jvm_memory_max_bytes{area=\"heap\"}) * 100",
     "legendFormat": "Heap Memory Usage"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytesiec" } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum[1m])",
     "legendFormat": "Request Duration"
    }
   ]
  }
 ]
}