name: Build & test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: mvn clean package

      - name: Run tests with coverage
        run: mvn test jacoco:report

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: artifact
          path: |
            ./core/domain/target/site/jacoco
            ./core/use-case/target/site/jacoco
            ./adapter/input/controller/target/site/jacoco
            ./adapter/output/repository/target/site/jacoco
          if-no-files-found: warn

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
